name CI coverage:all

on:
  pull_request:
    branches: 
      - '*'

  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - uses: actions/checkout@v2
        width:
          ref: ${{ github.event.pull_request.head.shu }}
      - name: Use Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/'
        
      - name: Install Yarn
        run: npm install yarn -g
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-ouitput name=dir::${yaarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node-modules
        uses: actions/cache@v2
        width:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages
        run: yarn --prefer-offline
      
      - name: Run Type Check
        run: yarn typecheck